application_title: Rex.Action Demo

db: pgsql:action_demo

htsql_extensions:
  rex_deploy:

access:
  rex.widget: anybody
  rex.action_demo: anybody
  rex.action: anybody

rex_widget:
  chrome: rex.action_demo.DemoChrome

rex_widget_chrome:
  magic: true
