application_title: RexPlatform Demo

db: pgsql:platform_demo

htsql_extensions:
  tweak.override:
    field-labels:
      school.__title__: (name)
      department.__title__: (name)
  rex_deploy: {}

auto_user_query: "'User'"
user_query: true()

access_queries:
  admin: user[$USER].admin
  viewer: user[$USER].viewer

access_masks:
  viewer:
  - school?!is_null(campus)

access:
  rex.platform_demo: anybody
  rex.platform: anybody

rex_widget:
  chrome: rex.widget_chrome.MenuChrome
