application_title: RexPlatform Demo

htsql_extensions:
  tweak.override:
    field-labels:
      school.__title__: (name)
      department.__title__: (name)
  rex_deploy: {}

auto_user_query: "'User'"
user_query: true()

access_queries:
  admin: user[$USER].admin
  viewer: user[$USER].viewer

menu:
- title: Home
  items:
  - url: rex.platform_demo:/
    access: anybody
- title: Schools
  items:
  - url: rex.platform_demo:/school_admin
    access: admin
  - url: rex.platform_demo:/school_viewer
    access: viewer

rex_widget:
  chrome: rex.widget_chrome.Chrome
