
- table: individual
  with:
  - column: code
    type: text
  - identity: [code: random]
  - column: sex
    type: [not-known, male, female, not-applicable]
    default: not-known
  - link: mother
    to: individual
    required: false
  - link: father
    to: individual
    required: false
  - link: adopted_mother
    to: individual
    required: false
  - link: adopted_father
    to: individual
    required: false
  - alias: title
    expression: code+' ('+switch(sex,'male','M','female','F','NA')+')'
  - data: individual.csv

- table: identity
  with:
  - link: individual
  - identity: [individual]
  - column: givenname
    type: text
    required: false
    title: Given Name
  - column: middle
    type: text
    required: false
    title: Middle Name
  - column: surname
    type: text
    required: false
  - column: birthdate
    type: date
    required: false
    title: Date of Birth
  - column: notes
    type: text
    required: false
  - data: identity.csv

