
- table: site
  with:
  - column: code
    type: text
  - identity: [code]
  - data: |
      code
      default

- table: study
  with:
  - column: code
    type: text
  - identity: [code]
  - column: title
    type: text
    unique: true
  - column: closed
    type: boolean
    default: false
  - link: site
    default: default
  - data: |
      code,title,closed
      fos,Family Obesity Study,false
      asdl,Autism Spectrum Disorder Lab,false
      des,Dennis Exercise Study,false
      puis,Prometheus University Intelligence Study,true

- sql: |
    CREATE INDEX study_title_idx ON study
    USING gin(to_tsvector('english', title));
  unless: |
    SELECT TRUE FROM pg_catalog.pg_class
    WHERE relname = 'study_title_idx';

