version: "3.3"
services:
  postgres:
    image: postgres:9
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
  develop:
    image: rexdb/develop:2019.02.04
    volumes:
      - type: bind
        source: .
        target: /repo
        read_only: true
      - type: volume
        source: appenv
        target: /app
      - type: volume
        source: appdata
        target: /app/data
      - type: volume
        source: apprun
        target: /app/run
      - type: volume
        source: appdocs
        target: /app/doc/build
    links:
      - postgres
    environment:
      - PGHOST
      - PGUSER
  nginx:
    image: nginx:stable-perl
    command: [nginx, -g, 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module.so; env REMOTE_USER;']
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - type: bind
        source: ./etc/nginx.conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - type: volume
        source: apprun
        target: /run/app
      - type: volume
        source: appdocs
        target: /docs
        read_only: true
    links:
      - develop
    environment:
      - REMOTE_USER
volumes:
  appenv:
  appdata:
  apprun:
  appdocs:
  pgdata:

