ignore:
  - ^doc/conf.py$
  - ^demo/.*$
  # Have to ignore the rex.ctl commands because pylint crashes when it tries to import cogs.
  - ^src/rex/instrument/ctl.py$

pep8:
  disable:
    - W391

pylint:
  disable:
    - W0401
    - R0922
    - C0302
    - C0111
    - R0903
    - R0921

  options:
    max-public-methods: 30
    max-args: 10

pyflakes:
  disable:
    - FL0005

frosted:
  disable:
    - E103

