db: pgsql:asynctask_demo

asynctask_transport: pgsql:asynctask_demo

asynctask_workers:
  foo: demo_foo_worker

logging_root:
  level: DEBUG
#  handlers: [console, file]

#logging_handlers:
#  file:
#    class: logging.FileHandler
#    filename: test.log

