db: pgsql:asynctask_demo

asynctask_transport: pgsql:asynctask_demo

asynctask_workers:
  foo:
    worker: demo_foo_worker
    #rate_max_calls: 5
    #rate_period: 5

asynctask_scheduled_workers: []

logging_root:
  level: DEBUG
  #handlers: [detailed_console, file]

logging_handlers:
  file:
    class: logging.FileHandler
    filename: test.log
    formatter: detailed
  detailed_console:
    class: logging.StreamHandler
    formatter: detailed
    stream: ext://sys.stdout

logging_loggers:
  amqp:
    level: CRITICAL
  pika:
    level: CRITICAL

