db: pgsql:asynctask_demo

asynctask_transport: pgsql:asynctask_demo

asynctask_workers:
  foo: demo_foo_worker

asynctask_scheduled_workers: []

logging_root:
  level: DEBUG
#  handlers: [console, file]

#logging_handlers:
#  file:
#    class: logging.FileHandler
#    filename: test.log
#    formatter: detailed

logging_loggers:
  amqp:
    level: CRITICAL
  pika:
    level: CRITICAL

