# Users/Permissions
user_query: true()

# Chrome
rex_widget:
  chrome: rex.widget_chrome.MenuChrome
application_title: RexAcquireActions Demo
username_query: $USER
user_profile_url: rex.acquire_actions_demo:/
application_logout_url: rex.acquire_actions_demo:/

db: pgsql:acquire_actions_demo

