inherits:
  - strictness_veryhigh

ignore:
  - ^doc/conf.py$
  - ^demo/.*$

pep8:
  disable:
    - W391

pylint:
  disable:
    - W0401
    - C0111
    - R0903
  enable:
    - W0511

pyflakes:
  disable:
    - FL0005

frosted:
  disable:
    - E103

pyroma:
  run: true
  disable:
    - PYR09
    - PYR14
    - PYR15

