mount:
  rex.assessment_import: /

access:
  rex.assessment_import: authenticated

db: pgsql:assessment_import_demo

instrument_implementation:
  assessment: rex.assessment_import_demo.DemoAssessment
