- table: individual
  with:
  - column: code
    type: text
  - identity: [code: random]
  - column: sex
    type: [not-known, male, female, not-applicable]
    default: not-known
  - link: mother
    to: individual
    required: false
  - link: father
    to: individual
    required: false
  - link: adopted_mother
    to: individual
    required: false
  - link: adopted_father
    to: individual
    required: false
  - link: site
    default: default
