- table: study_x_user
  with:
  - link: study
  - link: user
  - identity: [study, user]
  - column: manage_staff
    type: boolean
    required: true
    default: false
  - column: manage_grants
    type: boolean
    required: true
    default: false
  - column: deprecated_configure_studies
    was: configure_studies
    type: boolean
    required: false
    default: false
  - column: recruit_participants
    type: boolean
    required: true
    default: false
  - column: enroll_participants
    type: boolean
    required: true
    default: false
  - column: enroll_participants_directly
    type: boolean
    required: true
    default: false
  - column: transcribe_data
    type: boolean
    required: true
    default: false
  - column: clean_data
    type: boolean
    required: true
    default: false
  - column: manage_datamarts
    type: boolean
    required: true
    default: false
  - column: explore_data
    type: boolean
    required: true
    default: false
