- table: todo
  with:
  - link: individual
  - link: study_enrollment
    required: false
  - column: code
    type: integer
  - identity: [individual, code: offset]
  - column: title
    type: text
  - column: status_deprecated
    was: status
    type: [complete, not-started, skipped, missing, failed, started]
    default: not-started
  - column: status
    type:
      - incomplete
      - complete
      - skipped
      - failed
    default: incomplete
  - link: facilitator
    to: user
    required: false
  - link: visit
    required: false
  - column: expected_completion_date
    type: datetime
    required: false
  - link: time_period_deprecated
    to: time_period
    was: time_period
    required: false
  - link: requirement
    required: false
  - link: study
    present: false
  - column: reason_skipped
    type: text
    required: false
  - link: asset_type
  - column: num_required_entries
    type: integer
    required: false
  - link: acquire_channel
    required: false
  - column: other_notes
    required: false
    type: text
  - column: start_window_visit_date
    type: datetime
    required: false
  - column: end_window_visit_date
    type: datetime
    required: false
  - link: appointment_deprecated
    to: appointment
    was: appointment
    required: false
  - link: initial_study_version
    to: study_version
    required: false
