- table: tube_usage
  with:
  - link: tube
  - column: code
    type: integer
  - identity: [tube, code: offset]
  - link: user
  - column: used_volume_amount
    type: decimal
    required: false
  - column: used_volume_unit
    type: [ml, ul]
    required: false
  - column: date_requested
    type: date
    required: false
  - column: note
    type: text
    required: false
