forms_implementation:
  form: rex.demo.forms.interface.DemoForm
  draftform: rex.demo.forms.interface.DemoDraftForm

forms_presentation_adaptors:
  chan135:
    - demo
  lookupchannel:
    - lookup
  demoapp:
    - lookup

forms_local_resource_prefix: rex.demo.forms:/media

db: pgsql:demo.forms

htsql_extensions:
  tweak.etl:
  rex_deploy:

mount:
  rex.forms: /

access:
  rex.forms: anybody

i18n_supported_locales:
  - en
  - es
  - ar

  - ak_GH  # Akan (Ghana)
  - en_GH  # English (Ghana)

  - en_LR  # English (Liberia)

  - yo_NG  # Yoruba (Nigeria)
  - en_NG  # English (Nigeria)

  - en_TZ  # English (Tanzania)
  - sw_TZ  # Swahili (Tanzania)
