# Users/Permissions
user_query: true()

# Chrome
rex_widget:
  chrome: rex.widget_chrome.MenuChrome
application_title: RexMartActions Demo
username_query: $USER
user_profile_url: rex.mart_actions_demo:/
application_logout_url: rex.mart_actions_demo:/

db: pgsql:mart_actions_demo

