#
# Copyright (c) 2014, Prometheus Research, LLC
#

#
# See also `audit-trigger` by 2ndQuadrant:
# https://wiki.postgresql.org/wiki/Audit_trigger_91plus
#


# To enable audit table in your project, include this file with directive:
#   - include: rex.deploy:/deploy/audit.yaml


- sql: |
    DO LANGUAGE plpgsql $_$
    DECLARE
        current_version text;
    BEGIN
        -- Fetch the current trigger version.
        SELECT obj_description(n.oid, 'pg_namespace') INTO current_version
        FROM pg_catalog.pg_namespace n
        WHERE n.nspname = 'audit';

        -- Create the schema and update the version number.
        CREATE SCHEMA IF NOT EXISTS audit;
        COMMENT ON SCHEMA audit IS 'version: 2.11.0';

        IF current_version IS NULL THEN
            -- Creating the table from scratch.

            CREATE TYPE audit.audit_action_enum AS ENUM ('insert', 'update', 'delete');

            CREATE SEQUENCE audit.audit_seq;

            -- Keeps `INSERT`, `UPDATE`, and `DELETE` action logs.
            CREATE TABLE audit.audit (
                id int8 NOT NULL DEFAULT nextval('audit.audit_seq'::regclass),
                timestamp timestamp NOT NULL DEFAULT 'now'::text::timestamp,
                session text NOT NULL,
                action audit.audit_action_enum NOT NULL,
                name text NOT NULL,
                old jsonb,
                new jsonb,
                CONSTRAINT audit_uk UNIQUE (id)
            );

            ALTER SEQUENCE audit.audit_seq OWNED BY audit.audit.id;

            CREATE INDEX audit_timestamp_idx ON audit.audit (timestamp);
            CREATE INDEX audit_session_idx ON audit.audit (session);
            CREATE INDEX audit_name_idx ON audit.audit (name);

        ELSE
            --- Convert columns to use the "jsonb" type.
            ALTER TABLE audit.audit ALTER COLUMN old SET DATA TYPE jsonb USING old::jsonb;
            ALTER TABLE audit.audit ALTER COLUMN new SET DATA TYPE jsonb USING new::jsonb;
        END IF;

        -- (Re)build trigger functions.

        -- Row trigger that logs `INSERT`, `UPDATE` and `DELETE` actions.
        CREATE OR REPLACE FUNCTION audit.audit() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            session text;
        BEGIN
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD = NEW THEN
                    RETURN NULL;
                END IF;
            EXCEPTION WHEN undefined_function THEN
                -- Records are not comparable.
            END;
            BEGIN
                SELECT current_setting('rex.session') INTO session;
            EXCEPTION WHEN undefined_object THEN
            END;
            IF session IS NULL THEN
                SELECT session_user INTO session;
            END IF;
            INSERT INTO audit.audit (session, action, name, old, new)
            VALUES (session,
                    LOWER(TG_OP)::audit.audit_action_enum,
                    TG_TABLE_NAME::text,
                    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD.*) END,
                    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW.*) END);
            RETURN NULL;
        END;
        $$;

        -- Installs the audit trigger onto the given table (`NULL` for all tables).
        CREATE OR REPLACE FUNCTION audit.deploy_audit(class regclass) RETURNS void LANGUAGE plpgsql AS $$
        BEGIN
            IF class IS NOT NULL THEN
                EXECUTE 'CREATE TRIGGER audit AFTER INSERT OR UPDATE OR DELETE ON ' ||
                        class ||
                        ' FOR EACH ROW EXECUTE PROCEDURE audit.audit()';
            ELSE
                FOR class IN SELECT c.oid
                             FROM pg_catalog.pg_class c
                             JOIN pg_catalog.pg_namespace n ON (c.relnamespace = n.oid)
                             WHERE c.relkind = 'r' AND n.nspname = 'public' AND
                                   NOT EXISTS(SELECT TRUE
                                              FROM pg_catalog.pg_trigger t
                                              WHERE c.oid = t.tgrelid AND t.tgname = 'audit')
                             ORDER BY 1
                LOOP
                    PERFORM audit.deploy_audit(class);
                END LOOP;
            END IF;
        END;
        $$;

        -- Delete the `CREATE TABLE` trigger (not supported by Google Cloud SQL).
        DROP FUNCTION IF EXISTS audit.deploy_audit() CASCADE;

        -- Install the audit trigger.
        IF current_version IS NULL THEN
            PERFORM audit.deploy_audit(NULL);
        END IF;
    END;
    $_$;

  unless: |
    SELECT obj_description(n.oid, 'pg_namespace') ~ '^version: 2[.]11[.]0$'
    FROM pg_catalog.pg_namespace n
    WHERE n.nspname = 'audit';



