forms_implementation:
  form: rex.forms_demo.interface.DemoForm
  draftform: rex.forms_demo.interface.DemoDraftForm

forms_presentation_adaptors:
  chan135:
    - demo
  lookupchannel:
    - lookup
  demoapp:
    - lookup

forms_local_resource_prefix: rex.forms_demo:/media

db: pgsql:forms_demo

htsql_extensions:
  tweak.etl:
  rex_deploy:

mount:
  rex.forms: /

access:
  rex.forms: anybody

i18n_supported_locales:
  - en
  - es
  - ar

